### ISSUE TITLE
Adding the graph for dataset

### ISSUE THREAD

**Issue by zelima** [datasets/commodity-prices#2]
@rgrp Could you please give directions, how graphs should be done?

**Comment by rgrp** [comment]
Take a browse through the existing datasets on http://data.okfn.org/data/ and find those with a graph such as http://data.okfn.org/data/core/finance-vix. Then look at the source datapackage.json.

**Comment by zelima** [comment]
@rgrp The graph is added. Please review http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Fzelima%2Fcommodity-prices

**Comment by rgrp** [comment]
@zelima perfect. Can you please PR or get this into this main repo and then close this issue.

**Comment by zelima** [comment]
@rgrp done: http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Fdatasets%2Fcommodity-prices

Closing
